import { createIndex, performSearch } from 'instantsearch-itemsjs-adapter';
import { describe, expect, it, vi } from 'vitest';
import {
  backfillHighlights,
  createStaticSearchClient,
  denormalizeResponse,
  getFacetAttributes,
  getIndexOptions,
  getIndexUrls,
  getSortings,
  loadIndex,
  normalizeQueries,
  pruneHighlights,
  type WorkerResponse
} from '../src/utils/staticSearch';

class FakeWorker {
  listeners: Array<(event: { data: WorkerResponse }) => void> = [];

  postMessage = vi.fn();

  addEventListener(_type: string, listener: (event: { data: WorkerResponse }) => void) {
    this.listeners.push(listener);
  }

  removeEventListener(_type: string, listener: (event: { data: WorkerResponse }) => void) {
    this.listeners = this.listeners.filter((l) => l !== listener);
  }

  reply(data: WorkerResponse) {
    this.listeners.forEach((listener) => listener({ data }));
  }

  sent() {
    return this.postMessage.mock.calls.map(([message]) => message);
  }
}

const createClient = () => {
  const worker = new FakeWorker();
  return { worker, client: createStaticSearchClient(worker as unknown as Worker) };
};

const options = {
  searchableFields: ['title', 'author'],
  aggregations: {
    author: { title: 'Author', size: 20, conjunction: false },
    subject: { title: 'Subject', size: 20, conjunction: false },
    date_normalised: { show_facet_stats: true }
  },
  sortings: {
    title_asc: { field: 'title', order: 'asc' as const },
    title_desc: { field: 'title', order: 'desc' as const },
    date_asc: { field: 'date_normalised', order: 'asc' as const, title: 'Oldest first' }
  }
};

describe('getIndexUrls', () => {
  it('points at the files generated by the static search endpoint', () => {
    expect(getIndexUrls('catalogue')).toEqual({
      data: '/search/catalogue/data.json',
      options: '/search/catalogue/options.json'
    });
  });
});

describe('getFacetAttributes', () => {
  it('splits aggregations into list and range attributes', () => {
    const { attributes, rangeAttributes } = getFacetAttributes(options);

    expect(attributes).toEqual(['author', 'subject']);
    expect(rangeAttributes).toEqual(['date_normalised']);
  });

  it('limits facets to the include list, in no particular order', () => {
    const { attributes, rangeAttributes } = getFacetAttributes(options, { include: ['subject'] });

    expect(attributes).toEqual(['subject']);
    expect(rangeAttributes).toEqual([]);
  });

  it('drops facets in the exclude list', () => {
    const { attributes } = getFacetAttributes(options, { exclude: ['author'] });

    expect(attributes).toEqual(['subject']);
  });

  it('prefers include over exclude, matching the Typesense provider', () => {
    const { attributes } = getFacetAttributes(options, {
      exclude: ['author'],
      include: ['author', 'subject']
    });

    expect(attributes).toEqual(['author', 'subject']);
  });

  it('returns empty attributes when the configuration declares no aggregations', () => {
    expect(getFacetAttributes({ searchableFields: [] })).toEqual({
      attributes: [],
      rangeAttributes: []
    });
  });
});

describe('getSortings', () => {
  const noTranslations = () => undefined as unknown as string;

  it('uses the ItemsJS sorting key as the SortBy value', () => {
    const sortings = getSortings(options, noTranslations);

    expect(sortings.map(({ value }) => value)).toEqual(['title_asc', 'title_desc', 'date_asc']);
  });

  it('derives a label when the sorting carries no title', () => {
    const sortings = getSortings(options, noTranslations);

    expect(sortings[0].label).toEqual('Title (A-Z)');
    expect(sortings[1].label).toEqual('Title (Z-A)');
  });

  it('prefers the configured title over a derived label', () => {
    const sortings = getSortings(options, noTranslations);

    expect(sortings[2].label).toEqual('Oldest first');
  });

  it('prefers a translation over both', () => {
    const t = (key: string) => (key === 'title_asc' ? 'A to Z' : undefined as unknown as string);
    const sortings = getSortings(options, t);

    expect(sortings[0].label).toEqual('A to Z');
    expect(sortings[2].label).toEqual('Oldest first');
  });

  it('returns no options when the configuration declares no sortings', () => {
    expect(getSortings({ searchableFields: [] }, noTranslations)).toEqual([]);
  });
});

describe('normalizeQueries', () => {
  it('defaults the facets param, which the adapter reads unconditionally', () => {
    expect(normalizeQueries([{ indexName: 'catalogue', params: { query: 'a' } }])).toEqual([
      { indexName: 'catalogue', params: { query: 'a', facets: [] } }
    ]);
  });

  it('defaults the facets param when the request has no params at all', () => {
    expect(normalizeQueries([{ indexName: 'catalogue' }])).toEqual([
      { indexName: 'catalogue', params: { facets: [] } }
    ]);
  });

  it('leaves an existing facets param alone', () => {
    expect(normalizeQueries([{ indexName: 'catalogue', params: { facets: ['author'] } }])).toEqual([
      { indexName: 'catalogue', params: { facets: ['author'] } }
    ]);
  });
});

describe('getIndexOptions', () => {
  it('keys the aggregations by document field', () => {
    expect(getIndexOptions({
      searchableFields: ['name'],
      aggregations: {
        names_facet: { size: 20 },
        event_range_facet: { show_facet_stats: true },
        author: { size: 20 }
      }
    })).toEqual({
      searchableFields: ['name'],
      aggregations: {
        names: { size: 20 },
        event_range: { show_facet_stats: true },
        author: { size: 20 }
      }
    });
  });
});

describe('normalizeQueries facet attributes', () => {
  it('maps the facets and filters to the document fields', () => {
    expect(normalizeQueries([{
      params: {
        facets: ['names_facet', 'author'],
        facetFilters: [['names_facet:Paris', 'names_facet:Rome: Città'], 'author:Pratchett'],
        numericFilters: ['event_range_facet>=2000', 'event_range_facet<=2020']
      }
    }])).toEqual([{
      params: {
        facets: ['names', 'author'],
        facetFilters: [['names:Paris', 'names:Rome: Città'], 'author:Pratchett'],
        numericFilters: ['event_range>=2000', 'event_range<=2020']
      }
    }]);
  });
});

describe('denormalizeResponse', () => {
  it('keys the facets and stats by the requested attributes', () => {
    const queries = [
      { params: { facets: ['names_facet', 'event_range_facet'] } },
      { params: { facets: ['author'] } }
    ];

    const response = {
      results: [
        {
          hits: [],
          facets: { names: { Paris: 1 }, event_range: { 2024: 1 } },
          facets_stats: { event_range: { min: 2024, max: 2024 } }
        },
        { hits: [], facets: { author: { Pratchett: 2 } }, facets_stats: {} }
      ]
    };

    expect(denormalizeResponse(queries, response)).toEqual({
      results: [
        {
          hits: [],
          facets: { names_facet: { Paris: 1 }, event_range_facet: { 2024: 1 } },
          facets_stats: { event_range_facet: { min: 2024, max: 2024 } }
        },
        { hits: [], facets: { author: { Pratchett: 2 } }, facets_stats: {} }
      ]
    });
  });
});

describe('pruneHighlights', () => {
  const none = (value: string) => ({ value, matchLevel: 'none', matchedWords: [] });
  const full = (value: string) => ({ value, matchLevel: 'full', matchedWords: ['paris'] });

  it('keeps only the attributes with a match, including nested and array values', () => {
    const response = {
      results: [{
        hits: [{
          id: '1',
          name: 'Paris',
          names: [{ toponym: 'Lutetia' }, { toponym: 'Paris' }],
          type: 'City',
          _highlightResult: {
            id: none('1'),
            name: full('<mark>Paris</mark>'),
            names: [{ toponym: none('Lutetia') }, { toponym: full('<mark>Paris</mark>') }],
            type: none('City')
          }
        }]
      }]
    };

    expect(pruneHighlights(response).results[0].hits[0]._highlightResult).toEqual({
      name: full('<mark>Paris</mark>'),
      names: [{ toponym: none('Lutetia') }, { toponym: full('<mark>Paris</mark>') }]
    });
  });

  it('removes the highlight result from hits without a match', () => {
    const response = {
      results: [{ hits: [{ id: '1', name: 'London', _highlightResult: { id: none('1'), name: none('London') } }] }]
    };

    expect(pruneHighlights(response).results[0].hits[0]).toEqual({ id: '1', name: 'London' });
  });
});

describe('backfillHighlights', () => {
  it('leaves the values unescaped for InstantSearch to escape', () => {
    const response = { results: [{ hits: [{ objectID: '1', name: '<a> & "b" \'c\' `d`', _rankingInfo: {} }] }] };

    expect(backfillHighlights(response).results[0].hits[0]._highlightResult).toEqual({
      name: { value: '<a> & "b" \'c\' `d`', matchLevel: 'none', matchedWords: [] }
    });
  });

  it('gives array items without a highlight an empty one', () => {
    const response = {
      results: [{ hits: [{ objectID: '1', events: [{ start_date: [null, null], end_date: ['1900', null] }] }] }]
    };

    const none = { matchLevel: 'none', matchedWords: [] };

    expect(backfillHighlights(response).results[0].hits[0]._highlightResult).toEqual({
      events: [{
        start_date: [{ value: '', ...none }, { value: '', ...none }],
        end_date: [{ value: '1900', ...none }, { value: '', ...none }]
      }]
    });
  });

  it('restores the highlight result the adapter produces', async () => {
    const data = [
      {
        id: '1',
        name: 'Paris & <Co>',
        names: [{ toponym: 'Lutetia' }, { toponym: 'Paris' }],
        count: 3,
        flag: true,
        empty: null,
        tags: ['a', 'paris']
      },
      { id: '2', name: 'London', names: [{ toponym: 'Londinium' }], count: 0, flag: false, tags: [] }
    ];

    const index = createIndex(data, { searchableFields: ['name', 'names.toponym', 'tags'], query: '' });

    for (const query of ['', 'paris', 'lond', 'zzz']) {
      const response = await performSearch([{ indexName: 'places', params: { query, facets: [] } }], index, {});
      expect(backfillHighlights(pruneHighlights(response))).toEqual(response);
    }
  });
});

describe('map bounds', () => {
  it('matches documents with any related location inside the bounds', async () => {
    const data = [
      { id: '1', name: 'Boston', relationship: [{ coordinates: [0, 0] }, { coordinates: [42.36, -71.06] }] },
      { id: '2', name: 'Paris', relationship: [{ coordinates: [48.86, 2.35] }] },
      { id: '3', name: 'Nowhere', relationship: [{ name: 'No geometry' }] }
    ];

    const index = createIndex(data, { searchableFields: ['name'], query: '' });

    const response = await performSearch(
      [{ indexName: 'places', params: { query: '', facets: [], insideBoundingBox: '45,-70,40,-80' } }],
      index,
      { geoLocationField: 'relationship.coordinates' }
    );

    expect(response.results[0].hits.map((hit) => hit.id)).toEqual(['1']);
  });
});

describe('loadIndex', () => {
  it('asks the worker to load the index and resolves with its options', async () => {
    const worker = new FakeWorker();
    const loading = loadIndex(worker as unknown as Worker, 'catalogue', 'coordinates');

    expect(worker.sent()).toEqual([{ type: 'load', indexName: 'catalogue', geoLocationField: 'coordinates' }]);

    worker.reply({ type: 'loaded', options });

    await expect(loading).resolves.toEqual(options);
    expect(worker.listeners).toHaveLength(0);
  });

  it('rejects when the worker fails to load the index', async () => {
    const worker = new FakeWorker();
    const loading = loadIndex(worker as unknown as Worker, 'catalogue', 'coordinates');

    worker.reply({ type: 'loadFailed', message: 'Not found' });

    await expect(loading).rejects.toThrow('Not found');
  });
});

describe('createStaticSearchClient', () => {
  const response = (query: string) => ({ results: [{ query }] });

  it('runs the search in the worker', async () => {
    const { client, worker } = createClient();
    const search = client.search([{ indexName: 'catalogue', params: { query: 'a' } }]);

    expect(worker.sent()).toEqual([
      { type: 'search', id: 0, queries: [{ indexName: 'catalogue', params: { query: 'a' } }] }
    ]);

    worker.reply({ type: 'results', id: 0, response: response('a') });

    await expect(search).resolves.toEqual(response('a'));
  });

  it('backfills the highlight results removed in the worker', async () => {
    const { client, worker } = createClient();
    const search = client.search([{ params: { query: '' } }]);

    worker.reply({ type: 'results', id: 0, response: { results: [{ hits: [{ objectID: '1', name: 'Paris' }] }] } });

    const result = await search;
    expect(result.results[0].hits[0]._highlightResult).toEqual({
      name: { value: 'Paris', matchLevel: 'none', matchedWords: [] }
    });
  });

  it('only sends the newest of the searches made while one is running', async () => {
    const { client, worker } = createClient();
    const settled: string[] = [];

    const searches = ['a', 'b', 'c'].map((query) => client
      .search([{ params: { query } }])
      .then((result) => settled.push(`${query}:${result.results[0].query}`)));

    expect(worker.sent()).toHaveLength(1);

    worker.reply({ type: 'results', id: 0, response: response('a') });

    expect(worker.sent()).toEqual([
      { type: 'search', id: 0, queries: [{ params: { query: 'a' } }] },
      { type: 'search', id: 1, queries: [{ params: { query: 'c' } }] }
    ]);

    worker.reply({ type: 'results', id: 1, response: response('c') });
    await Promise.all(searches);

    // The replaced search settles after the newest one, with its response.
    expect(settled).toEqual(['a:a', 'c:c', 'b:c']);
  });

  it('rejects when the search fails in the worker', async () => {
    const { client, worker } = createClient();
    const search = client.search([{ params: { query: 'a' } }]);

    worker.reply({ type: 'searchFailed', id: 0, message: 'Boom' });

    await expect(search).rejects.toThrow('Boom');
  });

  it('ignores responses for other searches', async () => {
    const { client, worker } = createClient();
    const search = client.search([{ params: { query: 'a' } }]);

    worker.reply({ type: 'results', id: 5, response: response('x') });
    worker.reply({ type: 'loaded', options });
    worker.reply({ type: 'results', id: 0, response: response('a') });

    await expect(search).resolves.toEqual(response('a'));
  });
});
