[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/tina/*"
  to = "/.netlify/functions/tina"
  status = 200
  force = true

[[redirects]]
  from = "/api/s3/*"
  to = "/.netlify/functions/tina"
  status = 200
  force = true

[dev]
  command = "npm run dev"
  targetPort = 4321